### ISSUE TITLE
Android - General - Expecting Sub-Navigation Number to be Links to Steps

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#13]
When using TalkBack, I would expect the sub-navigation with the numbers to be a link to that  particular "Step".

**Comment by KyleLivingstonDOL** [comment]
Hi John, can you please clarify this 508 issue? I am not quite understanding it. -Kyle

**Comment by jfc3-dol** [comment]
The numbered circles remind me of a sub-navigation, and I would have thought they would be a link so I could go to that particular Step. It's an easy way to change from one Step to another without having to open the menu/navigation in the application. If I clicked or tapped on the number three I would be taken to the main Step 3 screen,

**Comment by KyleLivingstonDOL** [comment]
Thanks John. Because we have the MENU button in place with all the steps outlined we are using that as the navigable tool for users to move around the app (in addition to the homepage). As such, this timeline was a direct user request (since users were unsure where they were in the old version of Comply Chain).

That being said, I am still unsure what the 508 issue is for accessibility. I understand the color contrasts, which we are addressing, but timeline is functioning as designed. It was not designed as a clickable/touchable navigation tool (especially since hit zones would be much too small.)

**Comment by KyleLivingstonDOL** [comment]
Update to my comment: Since this was tagged a functional issue, and not accessibility, can you confirm that leaving the navigation timeline as is (addressing the contrast issues, though), would not be a 508 compliance violation?

Thanks!
Kyle

**Comment by jfc3-dol** [comment]
It's not an accessibility/Section 508 issue but a functional one.

For those with mobility issues, it would most likely be easier and quicker for them and others to tap the Step number in the top navigation and change Steps than of having to open the "Menu" and then find the step they needed and activate it.

If for now, the Steps at the top of the screen are not going to be links then I'm going to close the issue and can reopen if things change.
