### ISSUE TITLE
Android - Search Screen - Why is First Letter in Search box Capitalized

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#22]
Why is the first letter in the search box capitalized when I didn’t type it that way? It's confusing to see when you didn't type it that way.

Having this happen in a functional type issue.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Thanks for this. Can you please explain the 508 compliance issue with this, so we can better address it?

**Comment by jfc3-dol** [comment]
If you look at the colored LABELs on the side of the issue, I never said this was an accessibility issue but a functional one. 

Because the code can be used to create iOS, Android, and web pages I thought I mentioned I would be using LABELs to denote language, platform, and other things so as not to have to create issues in GitHub for each type of problem found.

It can be confusing to people if you change the capitalization of the information they typed especially those with poor vision or cognitive issues.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. Appreciate you pointing out the labels in GitHub; I didn't really see those there, but now that I do, I can better see what are accessibility vs functional issues.

As this does seem to be tagged as a function issue, rather than an accessibility one, can you please confirm that leaving the first letter capitalized in the search bar would not be a 508 compliance violation? As with many search/fill in bars on mobile devices (i.e., addresses, names, e-mail addresses, companies, etc.) start with a capital letter, we are working to keep that same functionality and "expected use" from a user's perspective.

Again, appreciate your insight and knowledge into this as I am new to working on 508 accessibility issues within mobile apps.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
If the first letter is going to be capitalized, I will close this issue.

Please note that the LABEL could also contain the language or platform (iOS, Android, and/or web) in case there are issues with a language or two. Having these LABELs will allow me to keep track of which language or platform is involved. Once one of the LABELs is corrected, I can turn them off and know what's remaining for the issue.

Glad I could help you understand more about Section 508 and accessibility.
