### ISSUE TITLE
Android - Steps Screen - Why are the Items in the Steps Closed

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#27]
Why are the items in the Steps closed, so people have to open them to see if there is any content? At a glance, if people miss the plus sign, you would wonder why there is no content on the page.

Opening another issue about the "Plus sign" and "Dash" buttons/icons that a screen reader user does not know what they are for and what state they are in.

**Comment by KyleLivingstonDOL** [comment]
This was a feature that was asked for from our users. Because Comply Chain is very text heavy, we have some collapsible sections with additional information. We can ask our contractors to change the screen reader call out of the plus and minus signs to something that is more accessible.

**Comment by jfc3-dol** [comment]
Okay, as I told the previous group if everything is closed on the screen, people might assume there is no content on the screen if they miss the plus sign in the heading. In the last version of this application, there was at least one section open so people knew there might be other content on the screen.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. Apologies, but I do not understand the 508 compliance issue here. It is my understanding that those reading the information should recognize a +/- button to expand/collapse additional content (as with many other leading websites/applications that are text heavy). Can you please elaborate on the 508 compliance issue?

Understood on the talkback feature (another issue you raise, which we are addressing).

Thanks,
Kyle

**Comment by KyleLivingstonDOL** [comment]
Update to my comment: Since this is tagged a functional issue, we will address the talk-back feature, but if we keep the +/- signs and default the extra content to close, would that be a 508 compliance violation? This was a direct user request to try and condense the information. And increases the functionality of the app from a user's perspective since there is much less scrolling involved.

Best,
Kyle

**Comment by jfc3-dol** [comment]
It's helpful to have at least open section open, so people see that there is content on the page. Not everyone's eyesight is perfect, or people aren't paying attention and could miss the plus and minus signs, which makes it look to them that there is not any content on the page.

In my years of doing web work, I have found that if you hide information from the user, they will assume there is now especially if you have all sections closed with only what looks like headings on the screen.

**Comment by KyleLivingstonDOL** [comment]
Thanks John, we appreciate the input and insight. At this time, we will want to leave them closed because one of the top complaints we've received from users in the field is the length of scrolling they have to do. To combat this, we've instituted kinetic scrolling as well as collapsible sections. We are also ensuring that when printing and saving as a PDF, we automatically open all boxes. Further, the webapp is dynamic, so there won't be any "cut off" box functions since the text width moves with the size of the browser window.

I suggest we close this out.

Best,
Kyle

**Comment by jfc3-dol** [comment]
Is there a way for the iOS and Android version that when the user is using a screen reader (VoiceOver and TalkBack) that the items are open and don't have plus or minus option. I saw a similar thing done with another DOL application I reviewed from the BLS Local Data. Let me look into that.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Thanks for this. I'd be interested in seeing the application. However, our users have specifically stated that they want to reduce the amount of scrolling needed. As we have coded in the "open/close" talkback functionality (so those with visual impairments can use a talkback reader and understand what they are interacting with), I think we can **close this item out**.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
Kyle,

Let me see if the newly updated application/code has been made public yet or not.

**Comment by jfc3-dol** [comment]
Kyle,

Thanks, for the update. I will close it when I get the next build and work my way through all the open issues.

**Comment by jfc3-dol** [comment]
Okay, will close issue and reopen a new one once I find the DOL application that expands the closed items when TalkBack is activated.
