### ISSUE TITLE
Android - Steps Screen - Why Isn’t the Step a Person is on Highlighted

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#28]
Why isn’t the Step a person is on highlighted in the number list at the top of the screen? Having what looks like sub-navigation of the eight different Steps on the screen is not useful if the current one is not highlighted. Plus, it would be helpful if a person taps or clicks on one they would be taken to that Step. Think I have already or will create and issues about that.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

I think it might be a bug you're encountering because during UAT, whenever I am in a Step, that Step # is highlighted in the progress bar above. Already replied re: tapping the progress bar # to be taken to that step. We decided not to do that as it would be replicating the same function -- essentially -- 3 times; we also think that it would be too small of an action area (where one touches the number) to be 508 compliant.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
Once I get the new version of the application, I will check that Step number is now highlighted with enough color contrast for the Step a person in on and even for the Topics within that Step.

**Comment by KyleLivingstonDOL** [comment]
Ok, thanks. Will look forward to your review during next 508 review.

**Comment by jfc3-dol** [comment]
The color contrast of the search results borders now passes color contrast ratio of 19.56:1.

So I'm going to close the issue.

Please see attached screenshot.

![comply chain - search box top border does not have enough color contrast](https://user-images.githubusercontent.com/10423487/59310145-71ce8b80-8c73-11e9-8c05-845937722d91.png)
